/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   用户信息表
 *
 * Generated by Starmie Generator, corresponds to the database table attachment
 *
 * @date 2023-11-22
 */
public class Attachment extends BaseEntity<Long, String> {

    private static final long serialVersionUID = 643163311127953143L;
    /**
     * attachment.type - 附件类型
     *
     * Generated by Starmie Generator.
     */
    private Integer type;
    /**
     * attachment.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * attachment.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;
    /**
     * attachment.content - 内容
     *
     * Generated by Starmie Generator.
     */
    private byte[] content;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column attachment.type - 附件类型
     * @return the value of attachment.type
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column attachment.type - 附件类型
     * @param type the value for attachment.type
     */
    public void setType(Integer type) {
        this. type = type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column attachment.status - 状态
     * @return the value of attachment.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column attachment.status - 状态
     * @param status the value for attachment.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column attachment.remark - 备注
     * @return the value of attachment.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column attachment.remark - 备注
     * @param remark the value for attachment.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column attachment.content - 内容
     * @return the value of attachment.content
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column attachment.content - 内容
     * @param content the value for attachment.content
     */
    public void setContent(byte[] content) {
        this. content = content;
    }

}