/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   公司员工
 *
 * Generated by Starmie Generator, corresponds to the database table employee
 *
 * @date 2023-12-06
 */
public class Employee extends BaseEntity<Integer, String> {

    private static final long serialVersionUID = 57207974394363031L;
    /**
     * employee.role - 系统角色-外键
     *
     * Generated by Starmie Generator.
     */
    private String role;
    /**
     * employee.user - 系统用户-外键
     *
     * Generated by Starmie Generator.
     */
    private String user;
    /**
     * employee.company - 供职公司-外键
     *
     * Generated by Starmie Generator.
     */
    private String company;
    /**
     * employee.show_name - 员工姓名
     *
     * Generated by Starmie Generator.
     */
    private String showName;
    /**
     * employee.tel - 联系电话
     *
     * Generated by Starmie Generator.
     */
    private String tel;
    /**
     * employee.remark - 职责描述
     *
     * Generated by Starmie Generator.
     */
    private String remark;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.role - 系统角色-外键
     * @return the value of employee.role
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.role - 系统角色-外键
     * @param role the value for employee.role
     */
    public void setRole(String role) {
        this. role = role;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.user - 系统用户-外键
     * @return the value of employee.user
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.user - 系统用户-外键
     * @param user the value for employee.user
     */
    public void setUser(String user) {
        this. user = user;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.company - 供职公司-外键
     * @return the value of employee.company
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.company - 供职公司-外键
     * @param company the value for employee.company
     */
    public void setCompany(String company) {
        this. company = company;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.show_name - 员工姓名
     * @return the value of employee.show_name
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.show_name - 员工姓名
     * @param showName the value for employee.show_name
     */
    public void setShowName(String showName) {
        this. showName = showName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.tel - 联系电话
     * @return the value of employee.tel
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.tel - 联系电话
     * @param tel the value for employee.tel
     */
    public void setTel(String tel) {
        this. tel = tel;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column employee.remark - 职责描述
     * @return the value of employee.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column employee.remark - 职责描述
     * @param remark the value for employee.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

}