/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   系统导航菜单
 *
 * Generated by Starmie Generator, corresponds to the database table navigation_menu
 *
 * @date 2023-11-18
 */
public class NavigationMenu extends BaseEntity<Long, String> {

    private static final long serialVersionUID = -7164952908838450409L;
    /**
     * navigation_menu.menu_no - 菜单编码
     *
     * Generated by Starmie Generator.
     */
    private String menuNo;
    /**
     * navigation_menu.menu_name - 菜单名称
     *
     * Generated by Starmie Generator.
     */
    private String menuName;
    /**
     * navigation_menu.uri - 菜单资源地址
     *
     * Generated by Starmie Generator.
     */
    private String uri;
    /**
     * navigation_menu.module_no - 模块编码
     *
     * Generated by Starmie Generator.
     */
    private String moduleNo;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_menu.menu_no - 菜单编码
     * @return the value of navigation_menu.menu_no
     */
    public String getMenuNo() {
        return menuNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_menu.menu_no - 菜单编码
     * @param menuNo the value for navigation_menu.menu_no
     */
    public void setMenuNo(String menuNo) {
        this. menuNo = menuNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_menu.menu_name - 菜单名称
     * @return the value of navigation_menu.menu_name
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_menu.menu_name - 菜单名称
     * @param menuName the value for navigation_menu.menu_name
     */
    public void setMenuName(String menuName) {
        this. menuName = menuName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_menu.uri - 菜单资源地址
     * @return the value of navigation_menu.uri
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_menu.uri - 菜单资源地址
     * @param uri the value for navigation_menu.uri
     */
    public void setUri(String uri) {
        this. uri = uri;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_menu.module_no - 模块编码
     * @return the value of navigation_menu.module_no
     */
    public String getModuleNo() {
        return moduleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_menu.module_no - 模块编码
     * @param moduleNo the value for navigation_menu.module_no
     */
    public void setModuleNo(String moduleNo) {
        this. moduleNo = moduleNo;
    }

}