/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import java.util.List;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   系统导航模块
 *
 * Generated by Starmie Generator, corresponds to the database table navigation_module
 *
 * @date 2023-10-31
 */
public class NavigationModule extends BaseEntity<Long, String> {

    private static final long serialVersionUID = 1487792930478140087L;
    /**
     * navigation_module.module_no - 模块编码
     *
     * Generated by Starmie Generator.
     */
    private String moduleNo;
    /**
     * navigation_module.module_name - 模块名称
     *
     * Generated by Starmie Generator.
     */
    private String moduleName;
    
    /**
     * 模块对应的菜单列表
     */
    private List<NavigationMenu> menus;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_module.module_no - 模块编码
     * @return the value of navigation_module.module_no
     */
    public String getModuleNo() {
        return moduleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_module.module_no - 模块编码
     * @param moduleNo the value for navigation_module.module_no
     */
    public void setModuleNo(String moduleNo) {
        this. moduleNo = moduleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column navigation_module.module_name - 模块名称
     * @return the value of navigation_module.module_name
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column navigation_module.module_name - 模块名称
     * @param moduleName the value for navigation_module.module_name
     */
    public void setModuleName(String moduleName) {
        this. moduleName = moduleName;
    }

    /**
     * @return the menus
     */
    public List<NavigationMenu> getMenus() {
        return menus;
    }

    /**
     * @param menus the menus to set
     */
    public void setMenus(List<NavigationMenu> menus) {
        this.menus = menus;
    }

}