/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   角色信息
 *
 * Generated by Starmie Generator, corresponds to the database table system_role
 *
 * @date 2023-12-21
 */
public class SystemRole extends BaseEntity<Integer, String> {

    private static final long serialVersionUID = 6924141888430964087L;
    /**
     * system_role.role_no - 登录名称
     *
     * Generated by Starmie Generator.
     */
    private String roleNo;
    /**
     * system_role.name - 登录密码
     *
     * Generated by Starmie Generator.
     */
    private String name;
    /**
     * system_role.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * system_role.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role.role_no - 登录名称
     * @return the value of system_role.role_no
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role.role_no - 登录名称
     * @param roleNo the value for system_role.role_no
     */
    public void setRoleNo(String roleNo) {
        this. roleNo = roleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role.name - 登录密码
     * @return the value of system_role.name
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role.name - 登录密码
     * @param name the value for system_role.name
     */
    public void setName(String name) {
        this. name = name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role.status - 状态
     * @return the value of system_role.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role.status - 状态
     * @param status the value for system_role.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role.remark - 备注
     * @return the value of system_role.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role.remark - 备注
     * @param remark the value for system_role.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

}