/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   系统编码
 *
 * Generated by Starmie Generator, corresponds to the database table system_serial_no
 *
 * @date 2023-12-11
 */
public class SystemSerialNo extends BaseEntity<Long, String> {

    private static final long serialVersionUID = 5202218018891670999L;
    /**
     * system_serial_no.code - 年月
     *
     * Generated by Starmie Generator.
     */
    private String code;
    /**
     * system_serial_no.serial_no - 序列号
     *
     * Generated by Starmie Generator.
     */
    private Integer serialNo;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_serial_no.code - 年月
     * @return the value of system_serial_no.code
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_serial_no.code - 年月
     * @param code the value for system_serial_no.code
     */
    public void setCode(String code) {
        this. code = code;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_serial_no.serial_no - 序列号
     * @return the value of system_serial_no.serial_no
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_serial_no.serial_no - 序列号
     * @param serialNo the value for system_serial_no.serial_no
     */
    public void setSerialNo(Integer serialNo) {
        this. serialNo = serialNo;
    }

}