/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   用户信息
 *
 * Generated by Starmie Generator, corresponds to the database table system_user
 *
 * @date 2023-12-06
 */
public class SystemUser extends BaseEntity<Integer, String> {

    private static final long serialVersionUID = 7272889371015543959L;
    /**
     * system_user.login_name - 登录名称
     *
     * Generated by Starmie Generator.
     */
    private String loginName;
    /**
     * system_user.login_pw - 登录密码
     *
     * Generated by Starmie Generator.
     */
    private String loginPw;
    /**
     * system_user.type - 用户类型
     *
     * Generated by Starmie Generator.
     */
    private Integer type;
    /**
     * system_user.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * system_user.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;
    
    /**
     * 员工信息
     */
    private Employee employee;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_user.login_name - 登录名称
     * @return the value of system_user.login_name
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_user.login_name - 登录名称
     * @param loginName the value for system_user.login_name
     */
    public void setLoginName(String loginName) {
        this. loginName = loginName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_user.login_pw - 登录密码
     * @return the value of system_user.login_pw
     */
    public String getLoginPw() {
        return loginPw;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_user.login_pw - 登录密码
     * @param loginPw the value for system_user.login_pw
     */
    public void setLoginPw(String loginPw) {
        this. loginPw = loginPw;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_user.type - 用户类型
     * @return the value of system_user.type
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_user.type - 用户类型
     * @param type the value for system_user.type
     */
    public void setType(Integer type) {
        this. type = type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_user.status - 状态
     * @return the value of system_user.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_user.status - 状态
     * @param status the value for system_user.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_user.remark - 备注
     * @return the value of system_user.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_user.remark - 备注
     * @param remark the value for system_user.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

    /**
     * @return the employee
     */
    public Employee getEmployee() {
        return employee;
    }

    /**
     * @param employee the employee to set
     */
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

}