/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   角色菜单关系
 *
 * Generated by Starmie Generator, corresponds to the database table system_role_menu
 *
 * @date 2023-12-21
 */
public class SystemRoleMenu extends BaseEntity<Integer, String> {

    private static final long serialVersionUID = 5822941412908629367L;
    /**
     * system_role_menu.role_no - 登录名称
     *
     * Generated by Starmie Generator.
     */
    private String roleNo;
    /**
     * system_role_menu.menu_no - 登录密码
     *
     * Generated by Starmie Generator.
     */
    private String menuNo;
    /**
     * system_role_menu.public_flag - 公共标志
     *
     * Generated by Starmie Generator.
     */
    private Integer publicFlag;
    /**
     * system_role_menu.create_flag - 创建标志
     *
     * Generated by Starmie Generator.
     */
    private Integer createFlag;
    /**
     * system_role_menu.update_flag - 更新标志
     *
     * Generated by Starmie Generator.
     */
    private Integer updateFlag;
    /**
     * system_role_menu.delete_flag - 删除标志
     *
     * Generated by Starmie Generator.
     */
    private Integer deleteFlag;
    /**
     * system_role_menu.import_flag - 导入标志
     *
     * Generated by Starmie Generator.
     */
    private Integer importFlag;
    /**
     * system_role_menu.export_flag - 导出标志
     *
     * Generated by Starmie Generator.
     */
    private Integer exportFlag;
    /**
     * system_role_menu.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.role_no - 登录名称
     * @return the value of system_role_menu.role_no
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.role_no - 登录名称
     * @param roleNo the value for system_role_menu.role_no
     */
    public void setRoleNo(String roleNo) {
        this. roleNo = roleNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.menu_no - 登录密码
     * @return the value of system_role_menu.menu_no
     */
    public String getMenuNo() {
        return menuNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.menu_no - 登录密码
     * @param menuNo the value for system_role_menu.menu_no
     */
    public void setMenuNo(String menuNo) {
        this. menuNo = menuNo;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.public_flag - 公共标志
     * @return the value of system_role_menu.public_flag
     */
    public Integer getPublicFlag() {
        return publicFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.public_flag - 公共标志
     * @param publicFlag the value for system_role_menu.public_flag
     */
    public void setPublicFlag(Integer publicFlag) {
        this. publicFlag = publicFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.create_flag - 创建标志
     * @return the value of system_role_menu.create_flag
     */
    public Integer getCreateFlag() {
        return createFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.create_flag - 创建标志
     * @param createFlag the value for system_role_menu.create_flag
     */
    public void setCreateFlag(Integer createFlag) {
        this.createFlag = createFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.update_flag - 更新标志
     * @return the value of system_role_menu.update_flag
     */
    public Integer getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.update_flag - 更新标志
     * @param updateFlag the value for system_role_menu.update_flag
     */
    public void setUpdateFlag(Integer updateFlag) {
        this. updateFlag = updateFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.delete_flag - 删除标志
     * @return the value of system_role_menu.delete_flag
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.delete_flag - 删除标志
     * @param deleteFlag the value for system_role_menu.delete_flag
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this. deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.import_flag - 导入标志
     * @return the value of system_role_menu.import_flag
     */
    public Integer getImportFlag() {
        return importFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.import_flag - 导入标志
     * @param importFlag the value for system_role_menu.import_flag
     */
    public void setImportFlag(Integer importFlag) {
        this. importFlag = importFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.export_flag - 导出标志
     * @return the value of system_role_menu.export_flag
     */
    public Integer getExportFlag() {
        return exportFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.export_flag - 导出标志
     * @param exportFlag the value for system_role_menu.export_flag
     */
    public void setExportFlag(Integer exportFlag) {
        this. exportFlag = exportFlag;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_role_menu.remark - 备注
     * @return the value of system_role_menu.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_role_menu.remark - 备注
     * @param remark the value for system_role_menu.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

}