/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   预设查询
 *
 * Generated by Starmie Generator, corresponds to the database table system_preset_search
 *
 * @date 2023-12-06
 */
public class SystemPresetSearch extends BaseEntity<Integer, String> {

    private static final long serialVersionUID = -1390347463023887209L;
    /**
     * system_preset_search.name - 登录名称
     *
     * Generated by Starmie Generator.
     */
    private String name;
    /**
     * system_preset_search.conditions - 备注
     *
     * Generated by Starmie Generator.
     */
    private String conditions;
    /**
     * system_preset_search.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * system_preset_search.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_preset_search.name - 登录名称
     * @return the value of system_preset_search.name
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_preset_search.name - 登录名称
     * @param name the value for system_preset_search.name
     */
    public void setName(String name) {
        this. name = name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_preset_search.condition - 备注
     * @return the value of system_preset_search.condition
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_preset_search.condition - 备注
     * @param condition the value for system_preset_search.condition
     */
    public void setConditions(String conditions) {
        this. conditions = conditions;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_preset_search.status - 状态
     * @return the value of system_preset_search.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_preset_search.status - 状态
     * @param status the value for system_preset_search.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column system_preset_search.remark - 备注
     * @return the value of system_preset_search.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column system_preset_search.remark - 备注
     * @param remark the value for system_preset_search.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

}