/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   用户信息表
 *
 * Generated by Starmie Generator, corresponds to the database table text_attach
 *
 * @date 2023-11-22
 */
public class TextAttach extends BaseEntity<Long, String> {

    private static final long serialVersionUID = 8419400424940401303L;
    /**
     * text_attach.type - 附件类型
     *
     * Generated by Starmie Generator.
     */
    private Integer type;
    /**
     * text_attach.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * text_attach.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;
    /**
     * text_attach.text_content
     *
     * Generated by Starmie Generator.
     */
    private String textContent;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column text_attach.type - 附件类型
     * @return the value of text_attach.type
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column text_attach.type - 附件类型
     * @param type the value for text_attach.type
     */
    public void setType(Integer type) {
        this. type = type;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column text_attach.status - 状态
     * @return the value of text_attach.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column text_attach.status - 状态
     * @param status the value for text_attach.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column text_attach.remark - 备注
     * @return the value of text_attach.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column text_attach.remark - 备注
     * @param remark the value for text_attach.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column text_attach.text_content
     * @return the value of text_attach.text_content
     */
    public String getTextContent() {
        return textContent;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column text_attach.text_content
     * @param textContent the value for text_attach.text_content
     */
    public void setTextContent(String textContent) {
        this. textContent = textContent;
    }

}