/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.model;

import io.github.starmoon1617.starmie.core.base.BaseEntity;

/**
 *   用户信息表
 *
 * Generated by Starmie Generator, corresponds to the database table user
 *
 * @date 2023-10-31
 */
public class User extends BaseEntity<Long, String> {

    private static final long serialVersionUID = -5129472667031917897L;
    /**
     * user.email - 邮箱
     *
     * Generated by Starmie Generator.
     */
    private String email;
    /**
     * user.login_name - 登录名称
     *
     * Generated by Starmie Generator.
     */
    private String loginName;
    /**
     * user.name - 名称
     *
     * Generated by Starmie Generator.
     */
    private String name;
    /**
     * user.age - 年龄
     *
     * Generated by Starmie Generator.
     */
    private Integer age;
    /**
     * user.status - 状态
     *
     * Generated by Starmie Generator.
     */
    private Integer status;
    /**
     * user.remark - 备注
     *
     * Generated by Starmie Generator.
     */
    private String remark;

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.email - 邮箱
     * @return the value of user.email
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.email - 邮箱
     * @param email the value for user.email
     */
    public void setEmail(String email) {
        this. email = email;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.login_name - 登录名称
     * @return the value of user.login_name
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.login_name - 登录名称
     * @param loginName the value for user.login_name
     */
    public void setLoginName(String loginName) {
        this. loginName = loginName;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.name - 名称
     * @return the value of user.name
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.name - 名称
     * @param name the value for user.name
     */
    public void setName(String name) {
        this. name = name;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.age - 年龄
     * @return the value of user.age
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.age - 年龄
     * @param age the value for user.age
     */
    public void setAge(Integer age) {
        this. age = age;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.status - 状态
     * @return the value of user.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.status - 状态
     * @param status the value for user.status
     */
    public void setStatus(Integer status) {
        this. status = status;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method returns the value of the database column user.remark - 备注
     * @return the value of user.remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Starmie Generator.
     * This method sets the value of the database column user.remark - 备注
     * @param remark the value for user.remark
     */
    public void setRemark(String remark) {
        this. remark = remark;
    }

}