/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.mapper;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.demo.biz.model.Attachment;

/**
 * Mapper forAttachment
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
public interface AttachmentMapper extends BaseMapper<Attachment, Long, String> {

}