/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.mapper;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.demo.biz.model.Employee;

/**
 * Mapper forEmployee
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
public interface EmployeeMapper extends BaseMapper<Employee, Integer, String> {

}