/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.mapper;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRole;

/**
 * Mapper for SystemRole
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
public interface SystemRoleMapper extends BaseMapper<SystemRole, Integer, String> {

}