/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.mapper;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;

/**
 * Mapper for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
public interface SystemSerialNoMapper extends BaseMapper<SystemSerialNo, Long, String> {
    
    /**
     * 查询当前序列号
     * 
     * @param code
     * @return
     */
    SystemSerialNo selectSerialNo(String code);

}