/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.AttachmentManager;
import io.github.starmoon1617.starmie.demo.biz.model.Attachment;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for Attachment
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Controller
@RequestMapping("/attachment")
public class AttachmentController extends AbstractBaseController<Attachment, Long, String> {

    @Resource
    private AttachmentManager attachmentManager;

    @Override
    protected String getPath() {
        return "attachment";
    }

    @Override
    protected BaseManager<Attachment, Long, String> getManager() {
        return attachmentManager;
    }

}