/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.EmployeeManager;
import io.github.starmoon1617.starmie.demo.biz.model.Employee;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for Employee
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Controller
@RequestMapping("/employee")
public class EmployeeController extends AbstractBaseController<Employee, Integer, String> {

    @Resource
    private EmployeeManager employeeManager;

    @Override
    protected String getPath() {
        return "employee";
    }

    @Override
    protected BaseManager<Employee, Integer, String> getManager() {
        return employeeManager;
    }

}