/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.base.BaseDto;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.core.util.CommonUtils;
import io.github.starmoon1617.starmie.demo.biz.manager.NavigationModuleManager;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationMenu;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationModule;
import jakarta.annotation.Resource;
import jakarta.servlet.http.HttpServletRequest;

/**
 * Controller for NavigationModule
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Controller
@RequestMapping("/navigation_module")
public class NavigationModuleController extends AbstractBaseController<NavigationModule, Long, String> {

    @Resource
    private NavigationModuleManager navigationModuleManager;

    @Override
    protected String getPath() {
        return "navigationModule";
    }

    @Override
    protected BaseManager<NavigationModule, Long, String> getManager() {
        return navigationModuleManager;
    }
    
    /**
     * 查找导航菜单
     * 
     * @return
     */
    @ResponseBody
    @RequestMapping(value = "/navigations", method = RequestMethod.POST)
    public BaseDto<List<NavigationModule>> findAllModule(HttpServletRequest request) {
        List<NavigationModule> navigationModules = navigationModuleManager.findWithMenu();
        if (CommonUtils.isEmpty(navigationModules)) {
            return getSuccess(navigationModules);
        }
        String contextPath = request.getContextPath();
        for (NavigationModule navigationModule : navigationModules) {
            if(CommonUtils.isEmpty(navigationModule.getMenus())) {
                continue;
            }
            for (NavigationMenu navigationMenu : navigationModule.getMenus()) {
                navigationMenu.setUri(contextPath.concat(navigationMenu.getUri()).concat(".vue"));
                navigationMenu.setMenuNo("/" + navigationMenu.getMenuNo());
            }
        }
        return getSuccess(navigationModules);
    }
    

}