/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.NavigationMenuManager;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationMenu;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for NavigationMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-18
 */
@Controller
@RequestMapping("/navigation_menu")
public class NavigationMenuController extends AbstractBaseController<NavigationMenu, Long, String> {

    @Resource
    private NavigationMenuManager navigationMenuManager;

    @Override
    protected String getPath() {
        return "navigationMenu";
    }

    @Override
    protected BaseManager<NavigationMenu, Long, String> getManager() {
        return navigationMenuManager;
    }

}