/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.SystemRoleManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRole;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for SystemRole
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Controller
@RequestMapping("/system_role")
public class SystemRoleController extends AbstractBaseController<SystemRole, Integer, String> {

    @Resource
    private SystemRoleManager systemRoleManager;

    @Override
    protected String getPath() {
        return "systemRole";
    }

    @Override
    protected BaseManager<SystemRole, Integer, String> getManager() {
        return systemRoleManager;
    }

}