/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.SystemSerialNoManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
@Controller
@RequestMapping("/system_serial_no")
public class SystemSerialNoController extends AbstractBaseController<SystemSerialNo, Long, String> {

    @Resource
    private SystemSerialNoManager systemSerialNoManager;

    @Override
    protected String getPath() {
        return "systemSerialNo";
    }

    @Override
    protected BaseManager<SystemSerialNo, Long, String> getManager() {
        return systemSerialNoManager;
    }

}