/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.util.SessionUtils;
import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.base.BaseDto;
import io.github.starmoon1617.starmie.core.criterion.BaseCriteria;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.core.util.CommonUtils;
import io.github.starmoon1617.starmie.demo.biz.manager.SystemPresetSearchManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemPresetSearch;
import io.github.starmoon1617.starmie.demo.biz.model.SystemUser;
import io.github.starmoon1617.starmie.demo.common.constant.Constants;
import jakarta.annotation.Resource;
import jakarta.servlet.http.HttpServletRequest;

import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Controller for SystemPresetSearch
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Controller
@RequestMapping("/system_preset_search")
public class SystemPresetSearchController extends AbstractBaseController<SystemPresetSearch, Integer, String> {

    @Resource
    private SystemPresetSearchManager systemPresetSearchManager;

    @Override
    protected String getPath() {
        return "systemPresetSearch";
    }

    @Override
    protected BaseManager<SystemPresetSearch, Integer, String> getManager() {
        return systemPresetSearchManager;
    }

    /**
     * 获取预设条件列表
     * 
     * @param request
     * @return
     */
    @ResponseBody
    @RequestMapping(value = "/listPressets", method = RequestMethod.POST)
    public BaseDto<List<SystemPresetSearch>> listPresetConditions(HttpServletRequest request) {
        String menuNo = request.getParameter("menuNo");
        if (!CommonUtils.isNotBlank(menuNo)) {
            return getFailure(-1, "menuNo not Null!");
        }
        SystemUser user = SessionUtils.get(Constants.CURRENT_USER, SystemUser.class);
        return getSuccess(
                systemPresetSearchManager.findConditions(BaseCriteria.getInstance().addEqual("menuNo", menuNo).addEqual("createBy", user.getLoginName())));
    }

}