/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.SystemUserManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemUser;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for SystemUser
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Controller
@RequestMapping("/system_user")
public class SystemUserController extends AbstractBaseController<SystemUser, Integer, String> {

    @Resource
    private SystemUserManager systemUserManager;

    @Override
    protected String getPath() {
        return "systemUser";
    }

    @Override
    protected BaseManager<SystemUser, Integer, String> getManager() {
        return systemUserManager;
    }

}