/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.SystemRoleMenuManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRoleMenu;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for SystemRoleMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Controller
@RequestMapping("/system_role_menu")
public class SystemRoleMenuController extends AbstractBaseController<SystemRoleMenu, Integer, String> {

    @Resource
    private SystemRoleMenuManager systemRoleMenuManager;

    @Override
    protected String getPath() {
        return "systemRoleMenu";
    }

    @Override
    protected BaseManager<SystemRoleMenu, Integer, String> getManager() {
        return systemRoleMenuManager;
    }

}