/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import io.github.starmoon1617.starmie.core.app.web.AbstractBaseController;
import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.TextAttachManager;
import io.github.starmoon1617.starmie.demo.biz.model.TextAttach;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Controller for TextAttach
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Controller
@RequestMapping("/text_attach")
public class TextAttachController extends AbstractBaseController<TextAttach, Long, String> {

    @Resource
    private TextAttachManager textAttachManager;

    @Override
    protected String getPath() {
        return "textAttach";
    }

    @Override
    protected BaseManager<TextAttach, Long, String> getManager() {
        return textAttachManager;
    }

}