/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.manager.UserManager;
import io.github.starmoon1617.starmie.demo.biz.model.User;
import io.github.starmoon1617.starmie.demo.web.annotation.Menu;
import jakarta.annotation.Resource;

/**
 * Controller for User
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Controller
@RequestMapping("/user")
@Menu("MN00010001")
public class UserController extends AbstractVueBaseController<User, Long, String> {

    @Resource
    private UserManager userManager;

    @Override
    protected String getPath() {
        return "user";
    }

    @Override
    protected BaseManager<User, Long, String> getManager() {
        return userManager;
    }

}