/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.Attachment;

/**
 * Manager Interface for Attachment
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
public interface AttachmentManager extends BaseManager<Attachment, Long, String> {

}