/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.Attachment;
import io.github.starmoon1617.starmie.demo.biz.service.AttachmentService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for Attachment
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Service("attachmentManager")
public class AttachmentManagerImpl extends BaseManagerImpl<Attachment, Long, String> implements AttachmentManager {

    @Resource
    private AttachmentService attachmentService;

    @Override
    protected BaseService<Attachment, Long, String> getService() {
        return attachmentService;
    }

}