/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.Employee;
import io.github.starmoon1617.starmie.demo.biz.service.EmployeeService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for Employee
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("employeeManager")
public class EmployeeManagerImpl extends BaseManagerImpl<Employee, Integer, String> implements EmployeeManager {

    @Resource
    private EmployeeService employeeService;

    @Override
    protected BaseService<Employee, Integer, String> getService() {
        return employeeService;
    }

}