/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationModule;
import io.github.starmoon1617.starmie.demo.biz.service.NavigationModuleService;
import jakarta.annotation.Resource;

import java.util.List;

import org.springframework.stereotype.Service;

/**
 * Manager Implementation for NavigationModule
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Service("navigationModuleManager")
public class NavigationModuleManagerImpl extends BaseManagerImpl<NavigationModule, Long, String> implements NavigationModuleManager {

    @Resource
    private NavigationModuleService navigationModuleService;

    @Override
    protected BaseService<NavigationModule, Long, String> getService() {
        return navigationModuleService;
    }

    @Override
    public List<NavigationModule> findWithMenu() {
        return navigationModuleService.findWithMenu();
    }

}