/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import java.util.List;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationModule;

/**
 * Manager Interface for NavigationModule
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
public interface NavigationModuleManager extends BaseManager<NavigationModule, Long, String> {

    /**
     * Find all Module with menu
     * @return
     */
    List<NavigationModule> findWithMenu();
}