/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationMenu;
import io.github.starmoon1617.starmie.demo.biz.service.NavigationMenuService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for NavigationMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-18
 */
@Service("navigationMenuManager")
public class NavigationMenuManagerImpl extends BaseManagerImpl<NavigationMenu, Long, String> implements NavigationMenuManager {

    @Resource
    private NavigationMenuService navigationMenuService;

    @Override
    protected BaseService<NavigationMenu, Long, String> getService() {
        return navigationMenuService;
    }

}