/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;

/**
 * Manager Interface for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
public interface SystemSerialNoManager extends BaseManager<SystemSerialNo, Long, String> {

    /**
     * 根据code获取序列号
     * @param code
     * @return
     */
    String getSerialNo(String code, String user);
    
}