/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;
import io.github.starmoon1617.starmie.demo.biz.service.SystemSerialNoService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * Manager Implementation for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
@Service("systemSerialNoManager")
public class SystemSerialNoManagerImpl extends BaseManagerImpl<SystemSerialNo, Long, String> implements SystemSerialNoManager {

    @Resource
    private SystemSerialNoService systemSerialNoService;

    @Override
    protected BaseService<SystemSerialNo, Long, String> getService() {
        return systemSerialNoService;
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRES_NEW, rollbackFor = Exception.class)
    public String getSerialNo(String code, String user) {
        SystemSerialNo ssn = systemSerialNoService.findSerialNo(code);
        if (ssn == null) {
            ssn = new SystemSerialNo();
        }
        return null;
    }

}