/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRoleMenu;
import io.github.starmoon1617.starmie.demo.biz.service.SystemRoleMenuService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for SystemRoleMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Service("systemRoleMenuManager")
public class SystemRoleMenuManagerImpl extends BaseManagerImpl<SystemRoleMenu, Integer, String> implements SystemRoleMenuManager {

    @Resource
    private SystemRoleMenuService systemRoleMenuService;

    @Override
    protected BaseService<SystemRoleMenu, Integer, String> getService() {
        return systemRoleMenuService;
    }

}