/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRole;

/**
 * Manager Interface for SystemRole
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
public interface SystemRoleManager extends BaseManager<SystemRole, Integer, String> {

}