/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemUser;
import io.github.starmoon1617.starmie.demo.biz.service.SystemUserService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for SystemUser
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("systemUserManager")
public class SystemUserManagerImpl extends BaseManagerImpl<SystemUser, Integer, String> implements SystemUserManager {

    @Resource
    private SystemUserService systemUserService;

    @Override
    protected BaseService<SystemUser, Integer, String> getService() {
        return systemUserService;
    }

}