/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRole;
import io.github.starmoon1617.starmie.demo.biz.service.SystemRoleService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for SystemRole
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Service("systemRoleManager")
public class SystemRoleManagerImpl extends BaseManagerImpl<SystemRole, Integer, String> implements SystemRoleManager {

    @Resource
    private SystemRoleService systemRoleService;

    @Override
    protected BaseService<SystemRole, Integer, String> getService() {
        return systemRoleService;
    }

}