/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.criterion.BaseCriteria;
import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemPresetSearch;
import io.github.starmoon1617.starmie.demo.biz.service.SystemPresetSearchService;
import jakarta.annotation.Resource;

import java.util.List;

import org.springframework.stereotype.Service;

/**
 * Manager Implementation for SystemPresetSearch
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("systemPresetSearchManager")
public class SystemPresetSearchManagerImpl extends BaseManagerImpl<SystemPresetSearch, Integer, String> implements SystemPresetSearchManager {

    @Resource
    private SystemPresetSearchService systemPresetSearchService;

    @Override
    protected BaseService<SystemPresetSearch, Integer, String> getService() {
        return systemPresetSearchService;
    }

    @Override
    public List<SystemPresetSearch> findConditions(BaseCriteria criteria) {
        return systemPresetSearchService.findConditions(criteria);
    }

}