/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.TextAttach;

/**
 * Manager Interface for TextAttach
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
public interface TextAttachManager extends BaseManager<TextAttach, Long, String> {

}