/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.TextAttach;
import io.github.starmoon1617.starmie.demo.biz.service.TextAttachService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for TextAttach
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Service("textAttachManager")
public class TextAttachManagerImpl extends BaseManagerImpl<TextAttach, Long, String> implements TextAttachManager {

    @Resource
    private TextAttachService textAttachService;

    @Override
    protected BaseService<TextAttach, Long, String> getService() {
        return textAttachService;
    }

}