/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManager;
import io.github.starmoon1617.starmie.demo.biz.model.User;

/**
 * Manager Interface for User
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
public interface UserManager extends BaseManager<User, Long, String> {

}