/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.manager;

import io.github.starmoon1617.starmie.core.manager.BaseManagerImpl;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.User;
import io.github.starmoon1617.starmie.demo.biz.service.UserService;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Manager Implementation for User
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Service("userManager")
public class UserManagerImpl extends BaseManagerImpl<User, Long, String> implements UserManager {

    @Resource
    private UserService userService;

    @Override
    protected BaseService<User, Long, String> getService() {
        return userService;
    }

}