/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.AttachmentMapper;
import io.github.starmoon1617.starmie.demo.biz.model.Attachment;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for Attachment
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Service("attachmentService")
public class AttachmentServiceImpl extends BaseServiceImpl<Attachment, Long, String> implements AttachmentService {

    @Resource
    private AttachmentMapper attachmentMapper;

    @Override
    protected BaseMapper<Attachment, Long, String> getMapper() {
        return attachmentMapper;
    }

}