/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.EmployeeMapper;
import io.github.starmoon1617.starmie.demo.biz.model.Employee;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for Employee
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("employeeService")
public class EmployeeServiceImpl extends BaseServiceImpl<Employee, Integer, String> implements EmployeeService {

    @Resource
    private EmployeeMapper employeeMapper;

    @Override
    protected BaseMapper<Employee, Integer, String> getMapper() {
        return employeeMapper;
    }

}