/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.NavigationModuleMapper;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationModule;
import jakarta.annotation.Resource;

import java.util.List;

import org.springframework.stereotype.Service;

/**
 * Service Implementation for NavigationModule
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Service("navigationModuleService")
public class NavigationModuleServiceImpl extends BaseServiceImpl<NavigationModule, Long, String> implements NavigationModuleService {

    @Resource
    private NavigationModuleMapper navigationModuleMapper;

    @Override
    protected BaseMapper<NavigationModule, Long, String> getMapper() {
        return navigationModuleMapper;
    }

    @Override
    public List<NavigationModule> findWithMenu() {
        return navigationModuleMapper.selectWithMenu();
    }

}