/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationMenu;

/**
 * Service Interface for NavigationMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-18
 */
public interface NavigationMenuService extends BaseService<NavigationMenu, Long, String> {

}