/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.NavigationMenuMapper;
import io.github.starmoon1617.starmie.demo.biz.model.NavigationMenu;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for NavigationMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-18
 */
@Service("navigationMenuService")
public class NavigationMenuServiceImpl extends BaseServiceImpl<NavigationMenu, Long, String> implements NavigationMenuService {

    @Resource
    private NavigationMenuMapper navigationMenuMapper;

    @Override
    protected BaseMapper<NavigationMenu, Long, String> getMapper() {
        return navigationMenuMapper;
    }

}