/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.SystemUserMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemUser;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for SystemUser
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("systemUserService")
public class SystemUserServiceImpl extends BaseServiceImpl<SystemUser, Integer, String> implements SystemUserService {

    @Resource
    private SystemUserMapper systemUserMapper;

    @Override
    protected BaseMapper<SystemUser, Integer, String> getMapper() {
        return systemUserMapper;
    }

}