/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.criterion.BaseCriteria;
import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.SystemPresetSearchMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemPresetSearch;
import jakarta.annotation.Resource;

import java.util.List;

import org.springframework.stereotype.Service;

/**
 * Service Implementation for SystemPresetSearch
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
@Service("systemPresetSearchService")
public class SystemPresetSearchServiceImpl extends BaseServiceImpl<SystemPresetSearch, Integer, String> implements SystemPresetSearchService {

    @Resource
    private SystemPresetSearchMapper systemPresetSearchMapper;

    @Override
    protected BaseMapper<SystemPresetSearch, Integer, String> getMapper() {
        return systemPresetSearchMapper;
    }

    @Override
    public List<SystemPresetSearch> findConditions(BaseCriteria criteria) {
        return systemPresetSearchMapper.selectConditions(criteria);
    }

}