/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemUser;

/**
 * Service Interface for SystemUser
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
public interface SystemUserService extends BaseService<SystemUser, Integer, String> {

}