/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.SystemSerialNoMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
@Service("systemSerialNoService")
public class SystemSerialNoServiceImpl extends BaseServiceImpl<SystemSerialNo, Long, String> implements SystemSerialNoService {

    @Resource
    private SystemSerialNoMapper systemSerialNoMapper;

    @Override
    protected BaseMapper<SystemSerialNo, Long, String> getMapper() {
        return systemSerialNoMapper;
    }

    @Override
    public SystemSerialNo findSerialNo(String code) {
        return systemSerialNoMapper.selectSerialNo(code);
    }

}