/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import java.util.List;

import io.github.starmoon1617.starmie.core.criterion.BaseCriteria;
import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemPresetSearch;

/**
 * Service Interface for SystemPresetSearch
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-06
 */
public interface SystemPresetSearchService extends BaseService<SystemPresetSearch, Integer, String> {

    /**
     * 查询条件列表
     * 
     * @param criteria
     * @return
     */
    List<SystemPresetSearch> findConditions(BaseCriteria criteria);
}