/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.SystemRoleMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRole;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for SystemRole
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Service("systemRoleService")
public class SystemRoleServiceImpl extends BaseServiceImpl<SystemRole, Integer, String> implements SystemRoleService {

    @Resource
    private SystemRoleMapper systemRoleMapper;

    @Override
    protected BaseMapper<SystemRole, Integer, String> getMapper() {
        return systemRoleMapper;
    }

}