/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.SystemRoleMenuMapper;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRoleMenu;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for SystemRoleMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
@Service("systemRoleMenuService")
public class SystemRoleMenuServiceImpl extends BaseServiceImpl<SystemRoleMenu, Integer, String> implements SystemRoleMenuService {

    @Resource
    private SystemRoleMenuMapper systemRoleMenuMapper;

    @Override
    protected BaseMapper<SystemRoleMenu, Integer, String> getMapper() {
        return systemRoleMenuMapper;
    }

}