/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemSerialNo;

/**
 * Service Interface for SystemSerialNo
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-11
 */
public interface SystemSerialNoService extends BaseService<SystemSerialNo, Long, String> {
    
    /**
     * 查询当前序列号,并更新序列值
     * 
     * @param code
     * @return
     */
    SystemSerialNo findSerialNo(String code);

}