/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.SystemRoleMenu;

/**
 * Service Interface for SystemRoleMenu
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-12-21
 */
public interface SystemRoleMenuService extends BaseService<SystemRoleMenu, Integer, String> {

}