/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.TextAttachMapper;
import io.github.starmoon1617.starmie.demo.biz.model.TextAttach;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for TextAttach
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-11-22
 */
@Service("textAttachService")
public class TextAttachServiceImpl extends BaseServiceImpl<TextAttach, Long, String> implements TextAttachService {

    @Resource
    private TextAttachMapper textAttachMapper;

    @Override
    protected BaseMapper<TextAttach, Long, String> getMapper() {
        return textAttachMapper;
    }

}