/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.mapper.BaseMapper;
import io.github.starmoon1617.starmie.core.service.BaseServiceImpl;
import io.github.starmoon1617.starmie.demo.biz.mapper.UserMapper;
import io.github.starmoon1617.starmie.demo.biz.model.User;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;

/**
 * Service Implementation for User
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
@Service("userService")
public class UserServiceImpl extends BaseServiceImpl<User, Long, String> implements UserService {

    @Resource
    private UserMapper userMapper;

    @Override
    protected BaseMapper<User, Long, String> getMapper() {
        return userMapper;
    }

}