/*
 * Copyright (c) 2023, Starmoon1617 and/or Nathan Liao. All rights reserved.
 */
package io.github.starmoon1617.starmie.demo.biz.service;

import io.github.starmoon1617.starmie.core.service.BaseService;
import io.github.starmoon1617.starmie.demo.biz.model.User;

/**
 * Service Interface for User
 *
 * Generated by Starmie Generator.
 *
 * @date 2023-10-31
 */
public interface UserService extends BaseService<User, Long, String> {

}